hyperparameters:
    id: "b3_cycle"
    decoder: "Unet"
    epochs: 45
    encoder: "efficientnet-b3"
    encoder_depth: 5
    cuda: true
    checkpoint_path:
    downsample_ratio: 4
    loss_function: "JaccardLoss"
    batch_size: 32
    optimizer: 
        name: SGD
        params:
            lr: 0.1
            momentum: 0.9 
    lr_scheduler:
        name: OneCycleLR
        params:
            max_lr: 0.5
            epochs:
            steps_per_epoch: 
            verbose: true
    seed:
    metrics: |
      IoU
      Accuracy
    classes: 12
    checkpoint_frequency: 5
    activation: "softmax2d"
    best_metric: "IoU"
